package com.ekuater.labelchat.coreservice.systempush.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ekuater.labelchat.coreservice.systempush.dao.DBSystemPush;

import com.ekuater.labelchat.coreservice.systempush.dao.DBSystemPushDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DBSystemPushSession extends AbstractDaoSession {

    private final DaoConfig dBSystemPushDaoConfig;

    private final DBSystemPushDao dBSystemPushDao;

    public DBSystemPushSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBSystemPushDaoConfig = daoConfigMap.get(DBSystemPushDao.class).clone();
        dBSystemPushDaoConfig.initIdentityScope(type);

        dBSystemPushDao = new DBSystemPushDao(dBSystemPushDaoConfig, this);

        registerDao(DBSystemPush.class, dBSystemPushDao);
    }
    
    public void clear() {
        dBSystemPushDaoConfig.getIdentityScope().clear();
    }

    public DBSystemPushDao getDBSystemPushDao() {
        return dBSystemPushDao;
    }

}
