package com.ekuater.labelchat.coreservice.systempush.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBSYSTEM_PUSH.
 */
public class DBSystemPush {

    private Long id;
    private String content;
    private Long time;
    private Integer state;
    private Integer type;
    private String flag;

    public DBSystemPush() {
    }

    public DBSystemPush(Long id) {
        this.id = id;
    }

    public DBSystemPush(Long id, String content, Long time, Integer state, Integer type, String flag) {
        this.id = id;
        this.content = content;
        this.time = time;
        this.state = state;
        this.type = type;
        this.flag = flag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getFlag() {
        return flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

}
