package com.ekuater.labelchat.coreservice.strangers.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBSTRANGER.
 */
public class DBStranger {

    private Long id;
    /** Not-null value. */
    private String userId;
    /** Not-null value. */
    private String labelCode;
    private String nickname;
    private String mobile;
    private Integer gender;
    private Long birthday;
    private Integer age;
    private Integer constellation;
    private String province;
    private String city;
    private String school;
    private String signature;
    private String avatar;
    private String avatarThumb;
    private String labels;
    private String location;

    public DBStranger() {
    }

    public DBStranger(Long id) {
        this.id = id;
    }

    public DBStranger(Long id, String userId, String labelCode, String nickname, String mobile, Integer gender, Long birthday, Integer age, Integer constellation, String province, String city, String school, String signature, String avatar, String avatarThumb, String labels, String location) {
        this.id = id;
        this.userId = userId;
        this.labelCode = labelCode;
        this.nickname = nickname;
        this.mobile = mobile;
        this.gender = gender;
        this.birthday = birthday;
        this.age = age;
        this.constellation = constellation;
        this.province = province;
        this.city = city;
        this.school = school;
        this.signature = signature;
        this.avatar = avatar;
        this.avatarThumb = avatarThumb;
        this.labels = labels;
        this.location = location;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    public String getLabelCode() {
        return labelCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLabelCode(String labelCode) {
        this.labelCode = labelCode;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public Long getBirthday() {
        return birthday;
    }

    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Integer getConstellation() {
        return constellation;
    }

    public void setConstellation(Integer constellation) {
        this.constellation = constellation;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getSchool() {
        return school;
    }

    public void setSchool(String school) {
        this.school = school;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getAvatarThumb() {
        return avatarThumb;
    }

    public void setAvatarThumb(String avatarThumb) {
        this.avatarThumb = avatarThumb;
    }

    public String getLabels() {
        return labels;
    }

    public void setLabels(String labels) {
        this.labels = labels;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

}
