package com.ekuater.labelchat.coreservice.strangers.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ekuater.labelchat.coreservice.strangers.dao.DBStranger;

import com.ekuater.labelchat.coreservice.strangers.dao.DBStrangerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DBStrangerSession extends AbstractDaoSession {

    private final DaoConfig dBStrangerDaoConfig;

    private final DBStrangerDao dBStrangerDao;

    public DBStrangerSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBStrangerDaoConfig = daoConfigMap.get(DBStrangerDao.class).clone();
        dBStrangerDaoConfig.initIdentityScope(type);

        dBStrangerDao = new DBStrangerDao(dBStrangerDaoConfig, this);

        registerDao(DBStranger.class, dBStrangerDao);
    }
    
    public void clear() {
        dBStrangerDaoConfig.getIdentityScope().clear();
    }

    public DBStrangerDao getDBStrangerDao() {
        return dBStrangerDao;
    }

}
