package com.ekuater.labelchat.coreservice.following.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBFOLLOWER_USER.
 */
public class DBFollowerUser {

    private Long id;
    /** Not-null value. */
    private String userId;
    /** Not-null value. */
    private String labelCode;
    private String nickname;
    private String avatar;
    private String avatarThumb;
    private Integer gender;

    public DBFollowerUser() {
    }

    public DBFollowerUser(Long id) {
        this.id = id;
    }

    public DBFollowerUser(Long id, String userId, String labelCode, String nickname, String avatar, String avatarThumb, Integer gender) {
        this.id = id;
        this.userId = userId;
        this.labelCode = labelCode;
        this.nickname = nickname;
        this.avatar = avatar;
        this.avatarThumb = avatarThumb;
        this.gender = gender;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    public String getLabelCode() {
        return labelCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLabelCode(String labelCode) {
        this.labelCode = labelCode;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getAvatarThumb() {
        return avatarThumb;
    }

    public void setAvatarThumb(String avatarThumb) {
        this.avatarThumb = avatarThumb;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

}
