package com.ekuater.labelchat.coreservice.chatmessage.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PENDING_CHAT.
 */
public class PendingChat {

    private Long id;
    private int type;
    private int conversationType;
    private int state;
    private String content;
    private String preview;
    private long time;
    /** Not-null value. */
    private String targetId;
    private String senderId;
    private String messageId;
    private int direction;

    public PendingChat() {
    }

    public PendingChat(Long id) {
        this.id = id;
    }

    public PendingChat(Long id, int type, int conversationType, int state, String content, String preview, long time, String targetId, String senderId, String messageId, int direction) {
        this.id = id;
        this.type = type;
        this.conversationType = conversationType;
        this.state = state;
        this.content = content;
        this.preview = preview;
        this.time = time;
        this.targetId = targetId;
        this.senderId = senderId;
        this.messageId = messageId;
        this.direction = direction;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public int getConversationType() {
        return conversationType;
    }

    public void setConversationType(int conversationType) {
        this.conversationType = conversationType;
    }

    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getPreview() {
        return preview;
    }

    public void setPreview(String preview) {
        this.preview = preview;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    /** Not-null value. */
    public String getTargetId() {
        return targetId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }

    public String getSenderId() {
        return senderId;
    }

    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    public String getMessageId() {
        return messageId;
    }

    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    public int getDirection() {
        return direction;
    }

    public void setDirection(int direction) {
        this.direction = direction;
    }

}
